version: 2

updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0
    rebase-strategy: "disabled"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    rebase-strategy: "disabled"
